### ISSUE TITLE
Add Swedish translation

### ISSUE THREAD

**Issue by johnjohndoe** [Umweltzone/roadsigns#9]
It would be nice to have a Swedish translation of the library. :sweden: 

The _Translation Editor_ in [_Android Studio_](https://developer.android.com/studio/) let's you easily identify the missing translations as shown in the screenshot.

![Android Studio Translation Editor](https://user-images.githubusercontent.com/144518/95666483-5078fa80-0b5a-11eb-8c80-159c893e6905.png)

# TODOs

- [x] Add new translations in `roadsigns/src/main/res/values-sv/strings.xml`
  - Adding a new language can be done via the _Translation Editor_: the earth icon at top left.
  - Alternatively, you can just copy the English file from `values/strings.xml` to `values-sv/strings.xml` and edit the strings manually.
  - Do not modify, commit files outside of the `-sv` folder.
  - Do not translate strings located in the `app` module.
  - Do not translate strings marked as `translatable="false"`.
  - Please do not commit to the `master` branch. Create a new branch like `swedish-translation` for the pull request.
  - Check that your translation string is not wrapped in double quotes (`"`) or includes unneeded whitespace.

# Related
- [Localize the UI with Translations Editor](https://developer.android.com/studio/write/translations-editor.html)

---

:left_speech_bubble: If you want to work on this issue please leave a "I like to work on this" comment here.

**Comment by fejd** [comment]
@johnjohndoe Sure, I'll fix this one 😊

**Comment by fejd** [comment]
@johnjohndoe Just to clarify, do the vehicles have either green, yellow or red, or is it possible to have a combination of badges? Both the English and German strings use and/und so it sounds like a combination but I just want to be certain I get it right.

**Comment by johnjohndoe** [comment]
@fejd Vehicles can only have one badge at a time. `and` is used in the sentences to tell that all vehicles with all these "colors" are allowed to enter the zone.
